FROM ubuntu
WORKDIR /build
ADD ./ /build/
RUN apt update && apt -y install git cmake make libtool rake python3-pip gcc g++ libsystemd-dev libudev-dev clang golang-go curl libvirt-dev smartmontools && update-smart-drivedb && git submodule sync --recursive && git submodule update --init --recursive && cd src && pip3 install --break-system-packages conan==2.26.1 && conan profile detect --force && conan install . --build=missing && conan build external/ && cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake && cmake --build build  --parallel 3

FROM ubuntu
COPY --from=0 /build/src/build/alligator /usr/bin/alligator
ENTRYPOINT /usr/bin/alligator
