image: Visual Studio 2017

init:
- git config --global core.autocrlf input

clone_folder: c:\app
shallow_clone: true

matrix:
  fast_finish: false

platform:
- x64

configuration:
- Debug
#- Release

clone_script:
- cmd: git clone -q --recurse-submodules -j2 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

install:
#- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- mkdir c:\assets
- copy NUL c:\assets\unistd.h
- appveyor DownloadFile https://downloads.datastax.com/cpp-driver/windows/dependencies/libuv/v1.24.0/libuv-1.24.0-win64-msvc141.zip
- mkdir c:\assets\libuv64
- 7z x -oc:\assets\libuv64 libuv-1.24.0-win64-msvc141.zip
- appveyor DownloadFile https://downloads.datastax.com/cpp-driver/windows/dependencies/libuv/v1.24.0/libuv-1.24.0-win32-msvc141.zip
- mkdir c:\assets\libuv32
- 7z x -oc:\assets\libuv32 libuv-1.24.0-win32-msvc141.zip
- set PATH="C:\Program Files\LLVM\bin";%PATH%
- clang-cl -v
- set CC=clang-cl -mrtm
- set CXX=clang-cl -mrtm
#- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
#- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

environment:
  DEPLOY_PASS:
    secure: svmfRdX8j9wfBhtAwZ9mwN2rc7nuBzCY8rj23yO21s4sgbyzB7yb0aJiDHh+al+PZ9be0SM1LHNUs4mOj2MQMedF7J2sKXxdWugGq7VvDdO3P/C8Mtq0C/U8vcqnsOhfwuOz2Y/udRADCBjOHHcCrQ==

build_script:
- cd src
- cmake -DCMAKE_GENERATOR_PLATFORM=x64 .
- cmake --build .
- curl -su win:%DEPLOY_PASS% -T C:\app\src\bin\Debug\alligator.exe http://amoshi.ru/api/test2/
