image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\app
shallow_clone: true

matrix:
  fast_finish: false

platform:
- x64

configuration:
- Debug
- Release

build_script:
- git submodule update --init --recursive
- cd src
- cmake .
- mak3
