stages:
- tests
- build

image: centos:7.9.2009

cutter_centos:
  stage: tests
  script:
  - yum -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j
  - cutter .

sources_tarball:
  stage: build
  only:
  - tags
  script:
  - yum -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh
  - cmake3 .
  - make -j
  - cd ..
  - mkdir /tmp/alligator-$CI_COMMIT_TAG
  - cp -a ./ /tmp/alligator-$CI_COMMIT_TAG/

  - ls /tmp
  - ls /tmp/alligator-$CI_COMMIT_TAG/
  - cd /tmp/alligator-$CI_COMMIT_TAG/src

  - cd /tmp
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz alligator-$CI_COMMIT_TAG/

deploy_centos7:
  stage: build
  only:
  - tags
  script:
  - yum -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.rpm`
  - curl -F "package[distro_version_id]=140" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_centos8:
  stage: build
  image: centos:8
  only:
  - tags
  script:
  - yum -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=RPM
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.rpm`
  - curl -F "package[distro_version_id]=205" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu2004:
  image: ubuntu:20.04
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.deb`
  - curl -F "package[distro_version_id]=210" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu1804:
  image: ubuntu:18.04
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.deb`
  - curl -F "package[distro_version_id]=190" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu1604:
  image: ubuntu:16.04
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.deb`
  - curl -F "package[distro_version_id]=165" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_debian9:
  image: debian:9
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.deb`
  - curl -F "package[distro_version_id]=149" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_debian10:
  image: debian:10
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt -y install git
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG-Linux.deb`
  - curl -F "package[distro_version_id]=150" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json
