stages:
- test

image: amoshi/cbuiler

tests:
  stage: test
  script:
  - yum -y install libuv-devel
  - cd src/dstructures/
  - git clone https://github.com/amadvance/tommyds.git
  - cd ../
  - cmake3 .
  - make
  - mv alligator alligator-test
  - curl -T alligator-test -uamoshi:$BINTRAY_KEY https://api.bintray.com/content/alligatormon/generic/
  - make package
  - curl -T alligator-*.rpm -uamoshi:$BINTRAY_KEY https://api.bintray.com/content/alligatormon/rpm/
