stages:
- tests
- build

image: amoshi/cbuiler

cutter_test:
  stage: tests
  script:
  - yum -y install libuv-devel libuv-static
  - wget http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
  - tar xfvz jansson-2.12.tar.gz
  - cd jansson-2.12
  - ./configure
  - make
  - make install
  - cd -
  - cd src
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make
  - cutter .

build_test:
  stage: tests
  script:
  - yum -y install libuv-devel libuv-static
  - wget http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
  - tar xfvz jansson-2.12.tar.gz
  - cd jansson-2.12
  - ./configure
  - make
  - make install
  - cd -
  - cd src
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make

sources_tarball:
  stage: build
  script:
  - mkdir /tmp/alligator-1.9.32
  - cp -a ./ /tmp/alligator-1.9.32/
  - cd /tmp
  - tar xfvz alligator-1.9.32.tar.gz alligator-1.9.32/
  - >-
    curl -s -T alligator-1.9.32.tar.gz -u$BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/packages/alligatormon/generic/

build_rpm:
  stage: build
  only:
  - tags
  script:
  - yum -y install libuv-devel libuv-static
  - wget http://www.digip.org/jansson/releases/jansson-2.12.tar.gz
  - tar xfvz jansson-2.12.tar.gz
  - src/jansson-2.12
  - ./configure
  - make
  - make install
  - cd -
  - cd src
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz alligator
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/generic/
  - curl -sT alligator-$CI_COMMIT_TAG.tar.gz -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/generic/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/generic/alligator/$CI_COMMIT_TAG/publish
  - make package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/rpm/
  - curl -sT alligator-*.rpm -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/rpm/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/rpm/alligator/$CI_COMMIT_TAG/publish

build_deb:
  image: ubuntu
  only:
  - tags
  stage: build
  script:
  - apt update
  - apt install -y cmake g++ gcc libuv1-dev
  - cat misc/deb-sources >> /etc/apt/sources.list
  - ( apt update --allow-unauthenticated || exit 0 )
  - apt -y --allow-unauthenticated install cutter-keyring
  - ( apt update || exit 0 )
  - apt -y install cutter-testing-framework
  - cd src
  - cmake . -DCPACK_GENERATOR=DEB
  - make package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/deb/
  - curl -sT alligator-*.deb -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" -H "X-Bintray-Debian-Distribution:wheezy" -H "X-Bintray-Debian-Component:main" -H "X-Bintray-Debian-Architecture:amd64" "https://api.bintray.com/content/alligatormon/deb/alligator/"
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/deb/alligator/$CI_COMMIT_TAG/publish
