stages:
- test

image: amoshi/cbuiler

tests:
  stage: test
  script:
  - yum -y install libuv-devel libuv-static
  - cd src
  - cmake3 .
  - make
  - mv alligator alligator-test
  - curl -T alligator-test -uamoshi:$BINTRAY_KEY https://api.bintray.com/content/alligatormon/generic/alligator/test/
  - make package
  - curl -T alligator-*.rpm -uamoshi:$BINTRAY_KEY https://api.bintray.com/content/alligatormon/rpm/alligator/test/
