stages:
- tests
- build

image: centos:7.9.2009

cutter_centos:
  stage: tests
  script:
  - echo "$BINTRAY_USER:$BINTRAY_KEY" | sha256sum
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j
  - cutter .

build_centos:
  stage: tests
  except:
  - tags
  script:
  - echo "$BINTRAY_USER:$BINTRAY_KEY" | sha256sum
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j

packacloud_test:
  stage: tests
  except:
  - tags
  script:
  - cd src
  - touch /builds/amoshi/alligator_build/src/alligator-1.12.3-Linux.deb
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.deb`
  - curl -F "package[distro_version_id]=220" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

build_centos8:
  image: centos:8
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j

build_ubuntu1604:
  image: ubuntu:16.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

build_ubuntu1804:
  image: ubuntu:18.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

build_ubuntu2004:
  image: ubuntu:20.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

sources_tarball:
  stage: build
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 .
  - make -j
  - cd ..
  - mkdir /tmp/alligator-$CI_COMMIT_TAG
  - cp -a ./ /tmp/alligator-$CI_COMMIT_TAG/

  - ls /tmp
  - ls /tmp/alligator-$CI_COMMIT_TAG/
  - cd /tmp/alligator-$CI_COMMIT_TAG/src

  - cd /tmp
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz alligator-$CI_COMMIT_TAG/

deploy_centos7:
  stage: build
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz bin/alligator
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.rpm`
  - curl -F "package[distro_version_id]=140" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_centos8:
  stage: build
  image: centos:8
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.rpm`
  - curl -F "package[distro_version_id]=205" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu2004:
  image: ubuntu:20.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.deb`
  - curl -F "package[distro_version_id]=210" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu1804:
  image: ubuntu:18.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.deb`
  - curl -F "package[distro_version_id]=190" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json

deploy_ubuntu1604:
  image: ubuntu:16.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-$CI_COMMIT_TAG.deb`
  - curl -F "package[distro_version_id]=165" -F "package[package_file]=@$PKGNAME" https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/amoshi/alligator/packages.json
