stages:
- tests
- build

#image: amoshi/cbuiler
image: centos:7.9.2009

cutter_centos:
  stage: tests
  script:
  - echo "$BINTRAY_USER:$BINTRAY_KEY" | sha256sum
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j
  - cutter .

build_centos:
  stage: tests
  except:
  - tags
  script:
  - echo "$BINTRAY_USER:$BINTRAY_KEY" | sha256sum
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j

build_centos8:
  image: centos:8
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j

build_ubuntu1604:
  image: ubuntu:16.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

build_ubuntu1804:
  image: ubuntu:18.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

build_ubuntu2004:
  image: ubuntu:20.04
  except:
  - tags
  stage: tests
  script:
  - cd src
  - sh bootstrap.sh
  - cmake . -DCPACK_GENERATOR=DEB
  - make -j

sources_tarball:
  stage: build
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 .
  - make -j
  - cd ..
  - mkdir /tmp/alligator-$CI_COMMIT_TAG
  - cp -a ./ /tmp/alligator-$CI_COMMIT_TAG/

  - ls /tmp
  - ls /tmp/alligator-$CI_COMMIT_TAG/
  - cd /tmp/alligator-$CI_COMMIT_TAG/src

  - cd /tmp
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz alligator-$CI_COMMIT_TAG/
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/sources/
  - curl -sT alligator-$CI_COMMIT_TAG.tar.gz -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/sources/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/sources/alligator/$CI_COMMIT_TAG/publish

deploy_centos7:
  stage: build
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j
  - tar cfvz alligator-$CI_COMMIT_TAG.tar.gz bin/alligator
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/generic/
  - curl -sT alligator-$CI_COMMIT_TAG.tar.gz -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/generic/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/generic/alligator/$CI_COMMIT_TAG/publish
  - make -j package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/el7/
  - curl -sT alligator-*.rpm -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/el7/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/el7/alligator/$CI_COMMIT_TAG/publish

deploy_centos8:
  stage: build
  image: centos:8
  only:
  - tags
  script:
  - cd src
  - sh bootstrap.sh
  - cmake3 . -DCPACK_GENERATOR=RPM
  - make -j package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/el8/
  - curl -sT alligator-*.rpm -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" https://api.bintray.com/content/alligatormon/el8/
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/el8/alligator/$CI_COMMIT_TAG/publish

deploy_ubuntu2004:
  image: ubuntu:20.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - PKGNAME=`ls alligator-*.deb`
  - curl -F "package[distro_version_id]=220" -F "package[package_file]=@$PKGNAME" \ https://$PKGCLOUD_TOKEN:@packagecloud.io/api/v1/repos/julio/example_repo/packages.json

deploy_ubuntu1804:
  image: ubuntu:18.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/ubuntu18.04/
  - curl -sT alligator-*.deb -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" -H "X-Bintray-Debian-Distribution:bionic" -H "X-Bintray-Debian-Component:main" -H "X-Bintray-Debian-Architecture:amd64" "https://api.bintray.com/content/alligatormon/ubuntu18.04/alligator/"
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/ubuntu18.04/alligator/$CI_COMMIT_TAG/publish

deploy_ubuntu1604:
  image: ubuntu:16.04
  only:
  - tags
  stage: build
  script:
  - cd src
  - sh bootstrap.sh

  - cmake . -DCPACK_GENERATOR=DEB
  - make -j package
  - >-
    curl -s -XPOST -d '{"name":"alligator", "licenses": ["Apache-2.0"], "vcs_url": "https://github.com/alligatormon/alligator.git", "desc":"alligator is aggregator for system and software metrics"}' -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/packages/alligatormon/ubuntu16.04/
  - curl -sT alligator-*.deb -u$BINTRAY_USER:$BINTRAY_KEY -H "X-Bintray-Package:alligator" -H "X-Bintray-Version:$CI_COMMIT_TAG" -H "X-Bintray-Debian-Distribution:xenial" -H "X-Bintray-Debian-Component:main" -H "X-Bintray-Debian-Architecture:amd64" "https://api.bintray.com/content/alligatormon/ubuntu16.04/alligator/"
  - curl -s -XPOST -u$BINTRAY_USER:$BINTRAY_KEY -H "Content-Type:application/json" -H "Accept:application/json" https://api.bintray.com/content/alligatormon/ubuntu16.04/alligator/$CI_COMMIT_TAG/publish
