apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alligator.fullname" . }}
  labels:
    {{- include "alligator.labels" . | nindent 4 }}
data:
  alligator.conf: |
    log_level {{ .Values.config.logLevel }};
    ttl {{ .Values.config.ttl }};
    aggregate_period {{ .Values.config.aggregatePeriod }};

    {{- if .Values.cluster.enabled }}
    cluster {
      name {{ .Values.cluster.name }};
      type {{ .Values.cluster.type }};
    }
    {{- end }}

    entrypoint {
      handler {{ .Values.config.entrypoint.handler }};
      tcp {{ .Values.config.entrypoint.port }};
      {{- if .Values.config.entrypoint.api }}
      api on;
      {{- end }}
      {{- if .Values.cluster.enabled }}
      cluster {{ .Values.cluster.name }};
      {{- end }}
      {{- range .Values.config.entrypoint.allowCidrs }}
      allow {{ . }};
      {{- end }}
    }

    {{- if .Values.config.system.cadvisor.enabled }}
    system {
      cadvisor;
    }
    {{- end }}

    aggregate {
      {{- if .Values.operator.enabled }}
      kubernetes_operator https://kubernetes.default.svc/?node_local={{ ternary "on" "off" .Values.operator.nodeLocal }}{{- range .Values.operator.namespaces }}&namespace={{ . }}{{- end }};
      {{- end }}
      {{- if .Values.operator.ingress.enabled }}
      kubernetes_ingress https://kubernetes.default.svc
        {{- if .Values.cluster.enabled }}
        cluster={{ .Values.cluster.name }}
        {{- end }}
        ;
      {{- end }}
      {{- range .Values.config.aggregates }}
      {{ . }};
      {{- end }}
    }
