{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "alligator.fullname" . }}
  labels:
    {{- include "alligator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "alligator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /
{{- end }}
