/* Code generated by cmd/cgo; DO NOT EDIT. */

#ifdef __cplusplus
extern "C" {
#endif

extern char* alligator_call(char* script, char* data, char* arg, char* metrics, char* conf, char* parser_data, char* response, char* queries);

#ifdef __cplusplus
}
#endif
