HTTP/1.1 200 OK
Server: nginx
Date: Sat, 09 Feb 2019 16:24:15 GMT
Content-Type: text/html; charset=koi8-r
Connection: close
Vary: Host
Accept-Ranges: bytes

<HTML>
<HEAD>
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=koi8-r">
   <TITLE>OpenNet без "www" - минималистский вариант портала по открытому ПО, Linux, BSD и Unix системам</TITLE>
   <meta name="KeyWords" content="статьи программы документация unix linux freebsd solaris bsd информация cisco настройка новости утилиты сеть perl программирование описание администрирование русификация безопасность">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="icon" type="image/png" href="/favicon.png">
   <meta content="/opennet_icon_128.png" itemprop="image">
   
   
   
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_all_utf.rss" title="Главные + мини-новости">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_6.rss" title="OpenNews RSS: главные новости">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_mini.rss" title="Mini-News RSS: мини-новости">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_review.rss" title="Фильтр: События">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_arts.rss" title="Фильтр: Обзоры статей">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_sec.rss" title="Фильтр: Проблемы безопасности">
   <link rel="alternate" type="application/rss+xml" href="/opennews/opennews_prog.rss" title="Фильтр: Новые версии программ">
   <link rel="search" href="https://www.opennet.ru/opensearch.xml" title="OpenNet.ru search" type="application/opensearchdescription+xml">
   <script language="JavaScript" src="/ajax_lite.js"></script>
   <link rel="stylesheet" href="/opennet_lite2.css" type="text/css">
</HEAD>
<style>
.l_title {
    font: bold 14pt Arial, Helvetica;
    text-align: center;
    border-bottom: 1px solid #b0b190;
    margin-bottom: 5px;
    padding-top: 5px;
    width: 80%;
    margin-left: auto; 
    margin-right: auto;
}
</style>

<BODY BGCOLOR="#E3E4D0">
<BASE href="http://www.opennet.ru/">
<div style="width: 100%; text-align: right; font-size: 70%; margin-bottom:0px;margin-top:-5px;">
<script language=JavaScript src="//www.opennet.ru/cgi-bin/opennet/rb2?login_js"></script> 
</div>


<div style="text-align: center;">
<div style="margin-left: auto; margin-right: auto; width: 100%; height: 70px; border:1px solid #b0b190; min-width: 360px; max-width: 600px; background: #E9EAD6 url('/back.gif') repeat-x bottom left;">
<div style="float:left; width: 249px; height: 60px; margin-top: 10px;">
<A HREF="https://www.opennet.ru"><IMG SRC="./opennet2_lite.gif" style="height: 60px; width: 249px; border: 1px;" ALT="The OpenNET Project / Index page"></A>
</div>
<div style="float: left; text-align: center; height: 70px; width: 331px; padding: 5px; margin-left: 10px;">
<br><small>[ <a href="/opennews/">новости</a>&nbsp;/<a href="/opennews/?full_lines=15&amp;lines=15&amp;mid_lines=00">+++</a> | <a href="/forum/">форум</a> | <a href="http://wiki.opennet.ru">wiki</a> | <a href="/keywords/">теги</a> ]</small>
</div>
</div>
<div style="clear: both;"></div>


<aside>
<br><br>
<div style="margin-left: auto; margin-right: auto; width:100%; border:1px solid #b0b190; min-width: 360px; max-width: 1100px; overflow: auto; padding: 5px;">

<div style="float:left; width: 50%; min-width: 300px; padding: 0px;">

<div class="l_title">
<a href="/opennews/index.shtml">Главные новости</a>
</div>
<table class=tlist>

<tr><td><b style='color: #A0A0A0;'>-</b> <span  >09.02</span>&nbsp;<a href="/opennews/art.shtml?num=50117">В SUSE/openSUSE будет отключена по умолчанию поддержка нетипичных файловых сиситем</a> <span class=cnt>(75 +6)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >09.02</span>&nbsp;<a href="/opennews/art.shtml?num=50116">Релиз Chrome OS 72</a> <span class=cnt>(21 &ndash;5)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50115">Проект GTK+ объявил о переименовании в GTK</a> <span class=cnt>(101 +38)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50114">Google открыл код ClusterFuzz, платформы для выявления ошибок и уязвимостей</a> <span class=cnt>(3 +5)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50108">Выпуск децентрализованной видеовещательной платформы PeerTube 1.2 </a> <span class=cnt>(123 +16)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span style="font-weight: bold">07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50109">Выпуск офисного пакета LibreOffice 6.2</a> <span class=cnt>(127 +42)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50105">Уязвимость в криптовалюте Zcash, позволявшая генерировать новые средства</a> <span class=cnt>(38 +9)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50101">Для Fedora утверждён метод подсчёта пользователей, не использующий UUID</a> <span class=cnt>(81 +6)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50099">Выпуск видеоредактора Flowblade 2.0</a> <span class=cnt>(66 +11)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50095">Уязвимость в Libreoffice и Openoffice, позволяющая выполнить код при открытии документа</a> <span class=cnt>(60 +21)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50093">Доступен web-браузер Min 1.9</a> <span class=cnt>(43 &ndash;29)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50090">Выпуск системы управления инфраструктурой виртуализации oVirt 4.3.0</a> <span class=cnt>(156 +9)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50087">В 29 Android-приложениях для работы с камерой и фото выявлен вредоносный код</a> <span class=cnt>(119 +25)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50086">Intel открыл кодировщик видео AV1, оптимизированный для перекодирования на лету</a> <span class=cnt>(175 +24)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >02.02</span>&nbsp;<a href="/opennews/art.shtml?num=50079">Релиз дистрибутива для создания домашних кинотеатров LibreELEC 9.0</a> <span class=cnt>(58 +15)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >02.02</span>&nbsp;<a href="/opennews/art.shtml?num=50076">Выпуск платформы Lutris 0.5 для упрощения доступа к играм из Linux</a> <span class=cnt>(68 +23)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >01.02</span>&nbsp;<a href="/opennews/art.shtml?num=50071">Первый стабильный выпуск Corretto 8, LTS-дистрибутива Java 8 от Amazon</a> <span class=cnt>(64 +12)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >01.02</span>&nbsp;<a href="/opennews/art.shtml?num=50068">Выпуск системной библиотеки Glibc 2.29</a> <span class=cnt>(66 +22)</span></td></tr>

<tr><td><div style="width: 100%; text-align: right; font-size: 70%;">
<a href="/opennews/?full_lines=15&lines=15&mid_lines=00">раскрыть всё</a>
| <a href="/opennews/main.shtml?skip=18&news=open&template=13new2&lines=20&mid_lines=0">далее &gt;&gt;</a></div></td></td>
</table> 

</div>
<div style="float:left; width: 50%; min-width: 300px; padding: 0px;">

<div class="l_title">
<a href="/opennews/mini.shtml">Мини-новости</a>
</div>
<table class=tlist>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50113">Уязвимости в Android, FreeBSD, rdesktop и FreeRDP</a> <span class=cnt>(47 +17)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50112">Фонд свободного ПО сертифицировал материнскую плату и ПК Vikings D8</a> <span class=cnt>(95 +28)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50107">В открытую платформу обмена сообщениями Mattermost инвестировано 20 млн долларов</a> <span class=cnt>(120 +20)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50106">Для Firefox развивается режим строгой изоляции страниц</a> <span class=cnt>(71 +17)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50104">Для Chrome реализован режим экономии ресурсов</a> <span class=cnt>(86 +26)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50103">Google опубликовал браузерное дополнение для оценки компрометации паролей</a> <span class=cnt>(34 &ndash;6)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50102">Выпуск библиотек для кодирования видео libvpx 1.8.0 и x265 3.0</a> <span class=cnt>(29 +14)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50100">Релиз Polemarch 1.0.0, web-интерфейса для Ansible</a> <span class=cnt>(21 +11)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50097">Новая версия среды разработки для FreePascal - Lazarus 2.0.0</a> <span class=cnt>(146 +36)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50094">В Firefox 67 ожидается блокировщик скриптов для майнинга и скрытой идентификации</a> <span class=cnt>(56 +24)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50092">Выпуск Wine 4.1</a> <span class=cnt>(103 +22)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50091">Выпуск операционной системы MidnightBSD 1.1</a> <span class=cnt>(21 +12)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50088">В eBPF найдена возможность обхода защиты ядра Linux от атаки Spectre</a> <span class=cnt>(43 +11)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >03.02</span>&nbsp;<a href="/opennews/art.shtml?num=50082">Проект RustPython развивает реализацию интерпретатора Python на языке Rust</a> <span class=cnt>(112 +13)</span></td></tr>

<tr><td><div style="width: 100%; text-align: right; font-size: 70%;"><a href="/opennews/mini.shtml?skip=14&mid_lines=00">далее &gt;&gt;</a></div></td></td>
</table> 
<br>
<div class="l_title">
<a href="/tips/sml/#last">Советы</a>
</div>
<table class="tlist">

<!--htdig_noindex-->

<tr><td><b>-</b> 27.01 <A HREF="/tips/3088_linux_sleep_wakeup_pcie_device_hardware_acpi.shtml">Отключение wakeup для PCIe устройств</A></td></tr>
<tr><td><b>-</b> 25.01 <A HREF="/tips/3086_esni_doh_dns_https.shtml">Включение ESNI и DNS over HTTPS в Firefox</A></td></tr>
<tr><td><b>-</b> 24.01 <A HREF="/tips/3087_dns.shtml">Список общедоступных DNS-резолверов</A></td></tr>
<tr><td><b>-</b> 07.11 <A HREF="/tips/3083_ceph_cluster_replication.shtml">История про Ceph и реплику 1+2</A></td></tr>
<tr><td><b>-</b> 06.11 <A HREF="/tips/3082_plplot_wxwidgets_windows_graph.shtml">Как подружить plPlot и wxWidgets под ОС Windows</A></td></tr>

<!--/htdig_noindex-->


<tr><td><div style="width: 100%; text-align: right; font-size: 70%;"><a href="/tips/sml/?skip=5#last">далее &gt;&gt;</a></div></td></td>
</table>


</div>
</div>

</aside>

<div class=hdr_mobile>
<div class="l_title">
<a href="/opennews/?full_lines=15&amp;lines=15&amp;mid_lines=00">Последние новости</a>
</div>
<table class=tlist>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >09.02</span>&nbsp;<a href="/opennews/art.shtml?num=50117">В SUSE/openSUSE будет отключена по умолчанию поддержка нетипичных файловых сиситем</a> <span class=cnt>(75 +6)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >09.02</span>&nbsp;<a href="/opennews/art.shtml?num=50116">Релиз Chrome OS 72</a> <span class=cnt>(21 &ndash;5)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50115">Проект GTK+ объявил о переименовании в GTK</a> <span class=cnt>(101 +38)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50114">Google открыл код ClusterFuzz, платформы для выявления ошибок и уязвимостей</a> <span class=cnt>(3 +5)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50113">Уязвимости в Android, FreeBSD, rdesktop и FreeRDP</a> <span class=cnt>(47 +17)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >08.02</span>&nbsp;<a href="/opennews/art.shtml?num=50112">Фонд свободного ПО сертифицировал материнскую плату и ПК Vikings D8</a> <span class=cnt>(95 +28)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50108">Выпуск децентрализованной видеовещательной платформы PeerTube 1.2 </a> <span class=cnt>(123 +16)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span style="font-weight: bold">07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50109">Выпуск офисного пакета LibreOffice 6.2</a> <span class=cnt>(127 +42)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50107">В открытую платформу обмена сообщениями Mattermost инвестировано 20 млн долларов</a> <span class=cnt>(120 +20)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >07.02</span>&nbsp;<a href="/opennews/art.shtml?num=50106">Для Firefox развивается режим строгой изоляции страниц</a> <span class=cnt>(71 +17)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50105">Уязвимость в криптовалюте Zcash, позволявшая генерировать новые средства</a> <span class=cnt>(38 +9)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50104">Для Chrome реализован режим экономии ресурсов</a> <span class=cnt>(86 +26)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50103">Google опубликовал браузерное дополнение для оценки компрометации паролей</a> <span class=cnt>(34 &ndash;6)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50102">Выпуск библиотек для кодирования видео libvpx 1.8.0 и x265 3.0</a> <span class=cnt>(29 +14)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50101">Для Fedora утверждён метод подсчёта пользователей, не использующий UUID</a> <span class=cnt>(81 +6)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >06.02</span>&nbsp;<a href="/opennews/art.shtml?num=50100">Релиз Polemarch 1.0.0, web-интерфейса для Ansible</a> <span class=cnt>(21 +11)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50099">Выпуск видеоредактора Flowblade 2.0</a> <span class=cnt>(66 +11)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50097">Новая версия среды разработки для FreePascal - Lazarus 2.0.0</a> <span class=cnt>(146 +36)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50095">Уязвимость в Libreoffice и Openoffice, позволяющая выполнить код при открытии документа</a> <span class=cnt>(60 +21)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50094">В Firefox 67 ожидается блокировщик скриптов для майнинга и скрытой идентификации</a> <span class=cnt>(56 +24)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >05.02</span>&nbsp;<a href="/opennews/art.shtml?num=50093">Доступен web-браузер Min 1.9</a> <span class=cnt>(43 &ndash;29)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50092">Выпуск Wine 4.1</a> <span class=cnt>(103 +22)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50091">Выпуск операционной системы MidnightBSD 1.1</a> <span class=cnt>(21 +12)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50090">Выпуск системы управления инфраструктурой виртуализации oVirt 4.3.0</a> <span class=cnt>(156 +9)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50088">В eBPF найдена возможность обхода защиты ядра Linux от атаки Spectre</a> <span class=cnt>(43 +11)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50087">В 29 Android-приложениях для работы с камерой и фото выявлен вредоносный код</a> <span class=cnt>(119 +25)</span></td></tr>
<tr><td><b style='color: #A0A0A0;'>-</b> <span  >04.02</span>&nbsp;<a href="/opennews/art.shtml?num=50086">Intel открыл кодировщик видео AV1, оптимизированный для перекодирования на лету</a> <span class=cnt>(175 +24)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >03.02</span>&nbsp;<a href="/opennews/art.shtml?num=50082">Проект RustPython развивает реализацию интерпретатора Python на языке Rust</a> <span class=cnt>(112 +13)</span></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >03.02</span>&nbsp;<a href="/opennews/art.shtml?num=50081">Выпуск GNU Binutils 2.32</a> <span class=cnt>(9 +14)</span></td></tr>
<tr><td><div class=tdelim></div></td></tr>
<tr><td><b style='color: #A0A0A0;padding-right: 1.3pt;'>&middot;</b> <span  >02.02</span>&nbsp;<a href="/opennews/art.shtml?num=50080">Пятый альфа-выпуск инсталлятора Debian 10 "Buster" </a> <span class=cnt>(144 +13)</span></td></tr>

</table>
<div style="margin-left: auto; margin-right: auto; border-top: 0px solid #b0b190; width: 100%; max-width: 1100px; text-align: right; font-size: 70%;">
<a href="/opennews/?full_lines=15&lines=15&mid_lines=00">раскрыть всё</a>
| <a href="/opennews/index.shtml?skip=30&mid_lines=00">далее &gt;&gt;</a></div>

<br><br>
<div class="l_title">
<a href="/tips/sml/#last">Последние советы</a>
</div>
<table class="tlist">

<!--htdig_noindex-->

<tr><td><b>-</b> 27.01 <A HREF="/tips/3088_linux_sleep_wakeup_pcie_device_hardware_acpi.shtml">Отключение wakeup для PCIe устройств</A></td></tr>
<tr><td><b>-</b> 25.01 <A HREF="/tips/3086_esni_doh_dns_https.shtml">Включение ESNI и DNS over HTTPS в Firefox</A></td></tr>
<tr><td><b>-</b> 24.01 <A HREF="/tips/3087_dns.shtml">Список общедоступных DNS-резолверов</A></td></tr>
<tr><td><b>-</b> 07.11 <A HREF="/tips/3083_ceph_cluster_replication.shtml">История про Ceph и реплику 1+2</A></td></tr>
<tr><td><b>-</b> 06.11 <A HREF="/tips/3082_plplot_wxwidgets_windows_graph.shtml">Как подружить plPlot и wxWidgets под ОС Windows</A></td></tr>

<!--/htdig_noindex-->


<tr><td><div style="width: 100%; text-align: right; font-size: 70%;"><a href="/tips/sml/?skip=5#last">далее &gt;&gt;</a></div></td></td>
</table>
</div>



<div style="margin-left: auto; margin-right: auto; border-top: 0px solid #b0b190; width: 100%; max-width: 1100px; text-align: right; font-size: 70%;"><a href="/opennews/opennews_all.rss">RSS</a> | <a href="/add.shtml">Добавить</a> <a href="/announce_news.shtml?c=f">новость</a>/<a href="/announce_tips.shtml?cache=off">заметку</a></div>
<div style="clear: both;"></div>



<br><br>


<div style="margin-left: auto; margin-right: auto; width:100%; min-width: 360px; max-width: 1110px; padding: 0px;">


<div id="tabs_top" style="width: 100%; min-width: 360px; padding: 0px;">
<div class="tab-selected" id="tab1" onclick="tabClick(1)">Разделы</div>
<div class="tab" id="tab2" onclick="tabClick(2)">Важное</div>
<div class="tab" id="tab3" onclick="tabClick(3)">Форум</div>
<div class="tab" id="tab4" onclick="tabClick(4)">Новые версии</div>
<div class="tab" id="tab5" onclick="tabClick(5)">Безопасность</div>
<div class="tab" id="tab6" onclick="tabClick(6)">События</div>
<div class="tab" id="tab7" onclick="tabClick(7)">Обзоры</div>
<div class="tab-null">&nbsp;</div>
</div>

<div id="top_news">
<div style="padding: 5px 0px 5px 0px; border-left: 1px solid #b0b190; border-right: 1px solid #b0b190; border-bottom: 1px solid #b0b190;">
<div style="float: left; margin: 15px;">
<FORM method="get" action="/cgi-bin/opennet/jump.cgi">
    <SELECT name="to" onChange="submit()" style="font-size: 10pt; width: 250; background-color: #C7CBB1; color: #0000AD;">
<OPTION value="" selected>Быстрая навигация по сайту</OPTION>
	<option value="/opennews/">__________________ НОВОСТИ:</option>
<option value="/opennews/">Новости OpenNews</option>
<option value="/news/opennet.shtml">Все новости OpenNet в одном месте</option>
<option value="/lastsoft/">LastSoft - Свежий софт</option>
<option value="/security/">Сообщения о проблемах безопасности</option>
<option value="/news/grab.shtml">Новости с других сайтов</option>
	<option value="/cgi-bin/openforum/vsluhboard.cgi">__________________ ОБЩЕНИЕ:</option>
<option value="/cgi-bin/openforum/vsluhboard.cgi">Форум</option>
    <option value="/prog/sml">__________________ КАТАЛОГИ:</option>
<option value="/prog/sml/">Каталог программного обеспечения</option>
<option value="/links/sml/">Каталог ссылок на unix ресурсы</option>
<option value="/filebase.shtml">Каталог тематических статей</option>
<option value="/docs/">Архив документации</option>
<option value="/tips/sml/">Советы, заметки</option>
<option value="/man.shtml">MAN - Системные руководства</option>
	<option value="/mp/">_______________ МИНИ-ПОРТАЛЫ:</option>
<option value="/cisco.shtml">CISCO.opennet.ru</option>
<option value="/bsd.shtml">BSD.opennet.ru</option>
<option value="/linux.shtml">LINUX.opennet.ru</option>
<option value="/solaris.shtml">SOLARIS.opennet.ru</option>
<option value="/web.shtml">WEB.opennet.ru - web-технологии</option>
<option value="/security/">SECURITY.opennet.ru</option>
<option value="/palm.shtml">PALM.opennet.ru - карманные ПК</option>
<option value="/mp/admin/">Администратору</option>
<option value="/mp/programmer/">Разработчику</option>
<option value="/mp/user/">Пользователю</option>
<option value="/mp/">Другие....</option>
	<option value="">__________________ РАЗНОЕ:</option>
<option value="/announce_prog.shtml">Добавить новость, ссылку, статью</option>
<option value="/ipcalc.shtml">IP-калькулятор</option>
	</SELECT>&nbsp;<input type="submit" value="&gt;" style="background-color: #E3E4D0; color: #0000AD; border: 0;">
</form>
</div>

<div style="float: left; margin: 15px;">
<form method="get" action="/cgi-bin/opennet/jump.cgi">
<select name="to" onChange="submit()" style="font-size: 10pt; width: 250; background-color: #C7CBB1; color: #0000AD;">
<option value="" selected>Тематическая выборка
<option value="admin">Администратору
 <option value="mail">&nbsp;&nbsp;|-- Почта
 <option value="dns">&nbsp;&nbsp;|-- DNS
 <option value="apache">&nbsp;&nbsp;|-- HTTP-серверы
 <option value="ftp">&nbsp;&nbsp;|-- FTP, BitTorrent
 <option value="samba">&nbsp;&nbsp;|-- Samba, Windows
 <option value="auth">&nbsp;&nbsp;|-- LDAP, Radius, Tacacs
 <option value="proxy">&nbsp;&nbsp;|-- Proxy, squid, socks
<option value="">
 <option value="route">&nbsp;&nbsp;|-- Маршрутизация, NAT
 <option value="firewall">&nbsp;&nbsp;|-- Firewall, Пакетные фильтры
 <option value="voip">&nbsp;&nbsp;|-- VoIP, Asterisk
 <option value="vpn">&nbsp;&nbsp;|-- VPN, PPPoE PPTP, IPSec
 <option value="crypt">&nbsp;&nbsp;|-- Шифрование, SSH, SSL
<option value="">
 <option value="tune">&nbsp;&nbsp;|-- Оптимизация, тюнинг
 <option value="cluster">&nbsp;&nbsp;|-- Кластеры
 <option value="virtual">&nbsp;&nbsp;|-- Виртуализация
 <option value="traffic">&nbsp;&nbsp;|-- Учет и ограничение трафика
 <option value="monitoring">&nbsp;&nbsp;|-- Мониторинг, диагностика
 <option value="security">&nbsp;&nbsp;|-- Безопасность
<option value="">
 <option value="fs">&nbsp;&nbsp;|-- Файловые системы
 <option value="backup">&nbsp;&nbsp;|-- Резервное копирование
 <option value="hardware">&nbsp;&nbsp;|-- Аппаратура, Железо
 <option value="kernel">&nbsp;&nbsp;|-- Ядро ОС (kernel)
 <option value="quota">&nbsp;&nbsp;|-- Квоты, ACL, ограничения
<option value="">
<option value="user">Пользователю
 <option value="rus">&nbsp;&nbsp;|-- Русификация
 <option value="x">&nbsp;&nbsp;|-- X Window
 <option value="multimedia">&nbsp;&nbsp;|-- Мультимедиа, звук, видео
 <option value="dialup">&nbsp;&nbsp;|-- Dial-up, ISP, PPP
 <option value="mobile">&nbsp;&nbsp;|-- Мобильные устройства и SoC
<option value="">
<option value="programmer">Программисту
 <option value="web">&nbsp;&nbsp;|-- Web-технологии
 <option value="shell">&nbsp;&nbsp;|-- Shell-скрипты
 <option value="perl">&nbsp;&nbsp;|-- Perl
 <option value="python">&nbsp;&nbsp;|-- Python
 <option value="gcc">&nbsp;&nbsp;|-- GCC, Си/Си++
 <option value="php">&nbsp;&nbsp;|-- PHP
 <option value="java">&nbsp;&nbsp;|-- Java, JSP
 <option value="javascript">&nbsp;&nbsp;|-- JavaScript
 <option value="html">&nbsp;&nbsp;|-- HTML, CSS
 <option value="sql">&nbsp;&nbsp;|-- MySQL, PostgreSQL, NoSQL
 <option value="ai">&nbsp;&nbsp;|-- Машинное обучение, AI
<option value="">
<option value="linux">Linux
<option value="bsd">FreeBSD, OpenBSD, NetBSD
<option value="solaris">Solaris
<option value="cisco">Cisco, маршрутизаторы
<option value="android">Android

</select>&nbsp;<input type="submit" value="&gt;" style="background-color: #E3E4D0; color: #0000AD; border: 0;">
</form>
</div>

<div style="float: left; margin: 15px;">
<FORM method="get" action="/cgi-bin/opennet/jump.cgi">
<A HREF="/search.shtml">Поиск</A>:&nbsp;<INPUT type="text" size="10" name="words" value="">
<select name="next" style="font-size: 85%; width: 70; background-color: #C7CBB1; color: #0000AD;">
<option value="site" selected>Сайт</option>
<option value="keys">Ключи</option>
<option value="forum">Форум</option>
<option value="man">MAN-ы</option>
</select>
<input type="submit" value="&gt;&gt;" style="background-color: #C7CBB1; color: #0000AD; border: 0;">
</form>

</div>

<div style="clear: both;"></div>

<small><a href="https://www.opennet.ru">Главная страница (c www.)</a>  |  <a href="/news/opennet.shtml">Новости по разделам</a>  |  <a href="/news/grab.shtml">Новости с других сайтов</a>  |  <a href="/lastsoft/">Последние версии ПО</a> | <a href="/forum/">Форум</a> | <a href="/mp/">Контент</a>
<a href="https://www.opennet.ru/opennews/opennews_all.rss"><img src="/img/rss.png" height="16" width="16" alt="RSS" title="RSS" border="0"></a>
&nbsp;<a href="https://twitter.com/opennetru"><img src="/twitter.png" height="16" width="16" alt="twitter" title="Twitter" border="0"></a> &nbsp;<a href="https://vk.com/opennet"><img src="/img/vkontakte.gif" height="16" width="16" title="ВКонтакте" border="0"></a>
&nbsp;<a href="https://tlg.name/opennet_ru"><img src="/img/telegram2.png" height="16" width="16" title="Telegram" border="0"></a>
&nbsp;<a href="https://zen.yandex.ru/opennet"><img src="/img/zen.gif" height="16" width="16" title="Yandex Zen" border="0"></a>
&nbsp;<a href="https://www.facebook.com/OpenNet.News/"><img src="/img/facebook.gif" height="16" width="16" title="Facebook" border="0"></a>
</small>


</div>
</div>
</div>



<div style="clear: both;"></div>
<br><br><br>

</div>

<div style="float: right;">
<small>Created 1996-2019 by <B><A HREF="/contact.shtml">Maxim Chirkov</A></B>
[ <A HREF="/add.shtml">Добавить</A> | <A HREF="https://www.opennet.ru/donate.shtml" style="color: #C00000;">Поддержать</A> | <A HREF="/banners2.shtml">Вебмастеру</A> ]</small>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-123449-1', 'auto');
    ga('send', 'pageview');
</script>
</div>

<br>

</BODY>
</HTML>

