{
 "title": "Alligator cadvisor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{}, name)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s, 1m, 2m, 3m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_cpu_quota{name=~\"$name\"} / container_spec_cpu_period{name=~\"$name\"}",
     "legendFormat": "rcv {{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{name=~\"$name\"}",
     "legendFormat": "rcv {{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\"$name\"}",
     "legendFormat": "rcv {{name}}"
    }
   ]
  },
  { "title": "CPU/Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name=~\"$name\"}[$interval]) / (container_spec_cpu_quota{name=~\"$name\"} / container_spec_cpu_period{name=~\"$name\"})",
     "legendFormat": "user {{name}}"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{name=~\"$name\"}[$interval]) / (container_spec_cpu_quota{name=~\"$name\"} / container_spec_cpu_period{name=~\"$name\"})",
     "legendFormat": "system {{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=~\"$name\"}",
     "legendFormat": "rss {{name}}"
    },
    {
     "expr": "container_memory_cache{name=~\"$name\"}",
     "legendFormat": "cache {{name}}"
    },
    {
     "expr": "container_memory_mapped_file{name=~\"$name\"}",
     "legendFormat": "mmaped file {{name}}"
    }
   ]
  },
  {
   "title": "CPU throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{name=~\"$name\"}[$interval]) / rate(container_cpu_cfs_periods_total{name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(container_memory_failcnt{name=~\"$name\"}[$interval])",
     "legendFormat": "failcnt {{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Network in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"$name\"}[$interval]) * 8",
     "legendFormat": "rcv {{name}}"
    },
    {
     "expr": "- rate(container_network_transmit_bytes_total{name=~\"$name\"}[$interval]) * 8",
     "legendFormat": "tsmt {{name}}"
    }
   ]
  },
  {
   "title": "Network in packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{name=~\"$name\"}[$interval])",
     "legendFormat": "rcv {{name}}"
    },
    {
     "expr": "- rate(container_network_transmit_packets_total{name=~\"$name\"}[5m])",
     "legendFormat": "tsmt {{name}}"
    }
   ]
  },
  {
   "title": "Network errors in packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_errors_total{name=~\"$name\"}[$interval])",
     "legendFormat": "rcv {{name}}"
    },
    {
     "expr": "- rate(container_network_transmit_errors_total{name=~\"$name\"}[$interval])",
     "legendFormat": "tsmt {{name}}"
    }
   ]
  },
  {
   "title": "Network drops in packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_dropped_total{name=~\"$name\"}[$interval])",
     "legendFormat": "rcv {{name}}"
    },
    {
     "expr": "- rate(container_network_transmit_packets_dropped_total{name=~\"$name\"}[5m])",
     "legendFormat": "tsmt {{name}}"
    }
   ]
  },
  { "title": "Disk stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Disk I/oO in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name=~\"$name\"}[$interval])",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{name=~\"$name\"}[5m])",
     "legendFormat": "write {{name}}"
    }
   ]
  },
  {
   "title": "Disk I/oOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{name=~\"$name\"}[$interval])",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "rate(container_fs_writes_total{name=~\"$name\"}[$interval])",
     "legendFormat": "write {{name}}"
    }
   ]
  },
  {
   "title": "Disk busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_fs_read_seconds_total{name=~\"$name\"}[$interval])",
     "legendFormat": "read {{name}}"
    },
    {
     "expr": "rate(container_fs_write_seconds_total{name=~\"$name\"}[$interval])",
     "legendFormat": "write {{name}}"
    }
   ]
  },
  {
   "title": "Open files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_open_files{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers task state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_tasks_state{name=~\"$name\"}",
     "legendFormat": "{{name}} {{ state }}"
    }
   ]
  }
 ]
}