{
 "title": "Alligator firewall",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(firewall_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "bytes accept",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(firewall_bytes{target=\"ACCEPT\", instance=~\"$instance\"}[135s])",
     "legendFormat": "{{ instance }} {{ comment }} {{ chain }} {{ src }} {{ dst }}"
    }
   ]
  },
  {
   "title": "packages accept",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(firewall_packets{target=\"ACCEPT\", instance=~\"$instance\"}[135s])",
     "legendFormat": "{{ instance }} {{ comment }} {{ chain }} {{ src }} {{ dst }}"
    }
   ]
  },
  {
   "title": "bytes drop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(firewall_bytes_total{policy=\"DROP\", instance=~\"$instance\"}[135s])",
     "legendFormat": "{{ instance }} {{ table }} {{ chain }}"
    }
   ]
  },
  {
   "title": "packages drop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(firewall_packets_total{policy=\"DROP\", instance=~\"$instance\"}[135s])",
     "legendFormat": "{{ instance }} {{ table }} {{ chain }}"
    }
   ]
  }
 ]
}