{
 "title": "Alligator clickhouse",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(Clickhouse_HTTPConnection,instance)"
    }
   },
   { "name": "interval", "query": "30s, 1m, 2m, 3m,5m, 10m, 1h" }
  ]
 },
 "panels": [
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Table_Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (table, type) (Clickhouse_Table_Stats{instance=~\"$instance\", type=\"data_uncompressed_bytes\"})",
     "legendFormat": "{{ type }} {{ table }}"
    }
   ]
  },
  {
   "title": "BackgroundPoolTask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_BackgroundPoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "BackgroundSchedulePoolTask",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_BackgroundSchedulePoolTask{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Seek",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_Seek{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SlowRead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_SlowRead{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_TCPConnection{instance=~\"$instance\"}",
     "legendFormat": "TCP {{ $instance }}"
    },
    {
     "expr": "Clickhouse_HTTPConnection{instance=~\"$instance\"}",
     "legendFormat": "HTTP {{ $instance }}"
    }
   ]
  },
  {
   "title": "Created rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_CreatedWriteBufferOrdinary{instance=~\"$instance\"}[$interval])",
     "legendFormat": "CreatedWriteBufferOrdinary {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_CreatedReadBufferOrdinary{instance=~\"$instance\"}[$interval])",
     "legendFormat": "CreatedReadBufferOrdinary {{ $instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_RegexpCreated{instance=~\"$instance\"}[$interval])",
     "legendFormat": "RegexpCreated {{ $instance }}"
    }
   ]
  },
  {
   "title": "PageFaults rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_SoftPageFaults{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Soft {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_HardPageFaults{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Hard {{ $instance }}"
    }
   ]
  },
  {
   "title": "Function Executes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_FunctionExecute{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} functions"
    },
    {
     "expr": "rate(Clickhouse_Events_TableFunctionExecute{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} table_functions"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "Clickhouse_Asynchronous_Uptime{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dictionary_Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (Clickhouse_Dictionary_Stats{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} {{ type }}"
    }
   ]
  },
  {
   "title": "NetworkReceiveElapsedMicrosecond rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_NetworkReceiveElapsedMicroseconds{instance=~\"$instance\"}[$interval])",
     "legendFormat": "NetworkReceiveElapsedMicrosecond"
    }
   ]
  },
  {
   "title": "Revision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Clickhouse_Revision{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LeaderElection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_LeaderElection{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "PartMutation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_PartMutation{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SelectedParts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_SelectedParts{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryTracking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_MemoryTracking{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} MemoryTracking"
    },
    {
     "expr": "Clickhouse_MemoryTrackingForMerges{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} MemoryTrackingForMerges"
    },
    {
     "expr": "Clickhouse_MemoryTrackingInBackgroundSchedulePool{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} MemoryTrackingInBackgroundSchedulePool"
    }
   ]
  },
  { "title": "Dictionary Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "DictCacheRequests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_DictCacheRequests{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Dictionary_Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Dictionary_Count{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Disk stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Disk I/O rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance, dev, type) (rate(disk_io{instance=~\"$instance\", type!~\".*timing.*\"}[$interval]))",
     "legendFormat": "{{ instance }} {{dev}} {{ type }}"
    }
   ]
  },
  {
   "title": "WriteBufferFromFileDescriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Read {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Write {{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Usage space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance, mountpoint) (disk_usage {instance=~\"$instance\", type=\"total\", mountpoint!~\".*(/run|/dev|/sys|/tmp|/proc).*\"}) / sum by (instance, mountpoint) (disk_usage {instance=~\"$instance\", mountpoint!~\".*(/run|/dev|/sys|/tmp|/proc).*\"})",
     "legendFormat": "{{ instance }}:{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_OpenFileForWrite{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} write"
    },
    {
     "expr": "Clickhouse_OpenFileForRead{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} read"
    }
   ]
  },
  {
   "title": "DiskElapsedMicroseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_DiskReadElapsedMicroseconds{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Read {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_DiskWriteElapsedMicroseconds{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Write {{ instance }}"
    }
   ]
  },
  {
   "title": "File rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Asynchronous_MarkCacheFiles{instance=~\"$instance\"}[$interval])",
     "legendFormat": "MarkCacheFiles {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_FileOpen{instance=~\"$instance\"}[$interval])",
     "legendFormat": "FileOpen {{ instance }}"
    }
   ]
  },
  {
   "title": "DiskSpaceReservedForMerge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_DiskSpaceReservedForMerge{instance=~\"$instance\"}",
     "legendFormat": "DiskSpaceReservedForMerge {{ instance }}"
    }
   ]
  },
  {
   "title": "ReadBufferFromFileDescriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Read {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Write {{ instance }}"
    }
   ]
  },
  { "title": "Replica stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "ReplicatedChecks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ReplicatedChecks{instance=~\"$instance\"}",
     "legendFormat": "ReplicatedChecks {{ instance }}"
    }
   ]
  },
  {
   "title": "Replicated tables in leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_LeaderReplica{instance=~\"$instance\"}",
     "legendFormat": "LeaderReplica {{ instance }}"
    }
   ]
  },
  {
   "title": "Replicas_Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (Clickhouse_Replicas_Stats{instance=~\"$instance\", type!~\"log_pointer|log_max_index\"})",
     "legendFormat": "{{ instance }} {{ type }}"
    }
   ]
  },
  {
   "title": "Replicas delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Asynchronous_ReplicasMaxAbsoluteDelay{instance=~\"$instance\"}",
     "legendFormat": "ReplicasMaxAbsoluteDelay {{ instance }}"
    }
   ]
  },
  {
   "title": "clickhouse readonly replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "Clickhouse_ReadonlyReplica{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Merges stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Merges_Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (Clickhouse_Merges_Stats{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} {{ type }}"
    }
   ]
  },
  {
   "title": "DiskSpaceReservedForMerge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_DiskSpaceReservedForMerge{instance=~\"$instance\"}",
     "legendFormat": "DiskSpaceReservedForMerge {{ instance }}"
    }
   ]
  },
  {
   "title": "MergedRows rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_MergedRows{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MergeTreeDataWriterRows rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_MergeTreeDataWriterRows{instance=~\"$instance\"}[$interval])",
     "legendFormat": "MergeTreeDataWriterRows {{ instance }}"
    }
   ]
  },
  {
   "title": "Replicas Merges In Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Asynchronous_ReplicasSumMergesInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasSumMergesInQueue {{ instance }}"
    },
    {
     "expr": "Clickhouse_Asynchronous_ReplicasMaxMergesInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasMaxMergesInQueue {{ instance }}"
    }
   ]
  },
  {
   "title": "MergeTreeDataWriterBlocks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "MergeTreeDataWriterBlocks {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_MergeTreeDataWriterBlocksAlreadySorted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "MergeTreeDataWriterBlocksAlreadySorted {{ instance }}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Merge{instance=~\"$instance\"}",
     "legendFormat": "Merge {{ instance }}"
    }
   ]
  },
  {
   "title": "MemoryTrackingForMerges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Clickhouse_MemoryTrackingForMerges{instance=~\"$instance\"}",
     "legendFormat": "MemoryTrackingForMerges {{ instance }}"
    }
   ]
  },
  {
   "title": "Merges time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_MergesTimeMilliseconds{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Merges time {{ instance }}"
    }
   ]
  },
  {
   "title": "MergeTreeDataWriterUncompressedBytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "MergeTreeDataWriterUncompressedBytes {{ instance }}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Query{instance=~\"$instance\"}",
     "legendFormat": "Query {{ instance }}"
    },
    {
     "expr": "Clickhouse_QueryPreempted{instance=~\"$instance\"}",
     "legendFormat": "QueryPreempted {{ $instance }}"
    },
    {
     "expr": "Clickhouse_QueryThread{instance=~\"$instance\"}",
     "legendFormat": "QueryThread {{ $instance }}"
    },
    {
     "expr": "Clickhouse_SelectQuery{instance=~\"$instance\"}",
     "legendFormat": "SelectQuery {{ $instance }}"
    }
   ]
  },
  {
   "title": "Distributed Files To Insert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_DistributedFilesToInsert{instance=~\"$instance\"}",
     "legendFormat": "FilesToInsert {{ instance }}"
    }
   ]
  },
  {
   "title": "Queue In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ReplicasMaxInsertsInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasMaxInsertsInQueue {{ instance }}"
    },
    {
     "expr": "Clickhouse_ReplicasMaxMergesInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasMaxMergesInQueue {{ instance }}"
    },
    {
     "expr": "Clickhouse_ReplicasSumInsertsInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasSumInsertsInQueue {{ instance }}"
    },
    {
     "expr": "Clickhouse_ReplicasSumMergesInQueue{instance=~\"$instance\"}",
     "legendFormat": "ReplicasSumMergesInQueue {{ instance }}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ContextLockWait{instance=~\"$instance\"}",
     "legendFormat": "ContextLockWait {{ instance }}"
    },
    {
     "expr": "Clickhouse_RWLockAcquiredReadLocks{instance=~\"$instance\"}",
     "legendFormat": "RWLockAcquiredReadLocks {{ $instance }}"
    },
    {
     "expr": "Clickhouse_RWLockActiveReaders{instance=~\"$instance\"}",
     "legendFormat": "RWLockActiveReaders {{ $instance }}"
    },
    {
     "expr": "Clickhouse_RWLockActiveWriters{instance=~\"$instance\"}",
     "legendFormat": "RWLockActiveWriters {{ $instance }}"
    },
    {
     "expr": "Clickhouse_RWLockReadersWaitMilliseconds{instance=~\"$instance\"}",
     "legendFormat": "RWLockReadersWaitMilliseconds {{ $instance }}"
    },
    {
     "expr": "Clickhouse_RWLockWaitingReaders{instance=~\"$instance\"}",
     "legendFormat": "RWLockWaitingReaders {{ $instance }}"
    },
    {
     "expr": "Clickhouse_RWLockWaitingWriters{instance=~\"$instance\"}",
     "legendFormat": "RWLockWaitingWriters {{ $instance }}"
    },
    {
     "expr": "Clickhouse_ContextLock{instance=~\"$instance\"}",
     "legendFormat": "ContextLock {{ $instance }}"
    }
   ]
  },
  {
   "title": "ArenaAllocChunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_ArenaAllocChunks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "ArenaAllocChunks {{ $instance }}"
    }
   ]
  },
  {
   "title": "Queue sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_Asynchronous_ReplicasMaxQueueSize{instance=~\"$instance\"}",
     "legendFormat": "ReplicasMaxQueueSize {{ instance }}"
    },
    {
     "expr": "Clickhouse_Asynchronous_ReplicasSumQueueSize{instance=~\"$instance\"}",
     "legendFormat": "ReplicasSumQueueSize {{ instance }}"
    }
   ]
  },
  {
   "title": "InsertedBytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_InsertedBytes{instance=~\"$instance\"}",
     "legendFormat": "InsertedBytes {{ instance }}"
    },
    {
     "expr": "Clickhouse_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}",
     "legendFormat": "MergeTreeDataWriterUncompressedBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_MergedUncompressedBytes{instance=~\"$instance\"}",
     "legendFormat": "MergedUncompressedBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_ReadCompressedBytes{instance=~\"$instance\"}",
     "legendFormat": "ReadCompressedBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_WriteBufferFromFileDescriptorWriteBytes{instance=~\"$instance\"}",
     "legendFormat": "WriteBufferFromFileDescriptorWriteBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}",
     "legendFormat": "MergeTreeDataWriterCompressedBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}",
     "legendFormat": "ReadBufferFromFileDescriptorReadBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_StorageBufferBytes{instance=~\"$instance\"}",
     "legendFormat": "StorageBufferBytes {{ $instance }}"
    },
    {
     "expr": "Clickhouse_UncompressedCacheBytes{instance=~\"$instance\"}",
     "legendFormat": "UncompressedCacheBytes {{ $instance }}"
    }
   ]
  },
  {
   "title": "AllocBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_Events_ArenaAllocBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "ArenaAllocBytes {{ instance }}"
    },
    {
     "expr": "rate(Clickhouse_Events_IOBufferAllocBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "IOBufferAllocBytes {{ instance }}"
    }
   ]
  },
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 215 } },
  {
   "title": "ZooKeeperRequest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ZooKeeperRequest{instance=~\"$instance\"}",
     "legendFormat": "ZooKeeperRequest {{ instance }}"
    }
   ]
  },
  {
   "title": "ZooKeeperSession",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ZooKeeperSession{instance=~\"$instance\"}",
     "legendFormat": "ZooKeeperSession {{ instance }}"
    }
   ]
  },
  {
   "title": "MergeTreeDataWriterBlocksAlreadySorted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_MergeTreeDataWriterBlocksAlreadySorted{instance=~\"$instance\"}",
     "legendFormat": "MergeTreeDataWriterBlocksAlreadySorted {{ $instance }}"
    }
   ]
  },
  {
   "title": "ZooKeeperWatch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Clickhouse_ZooKeeperWatch{instance=~\"$instance\"}",
     "legendFormat": "ZooKeeperWatch {{ instance }}"
    }
   ]
  },
  {
   "title": "CompressedReadBufferBytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(Clickhouse_CompressedReadBufferBytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}