{
 "title": "Alligator zookeeper",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(zk_avg_latency,instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s, 1m, 2m, 3m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Zoo counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_watch_count{instance=~\"$instance\"}",
     "legendFormat": "watch {{ instance }}"
    },
    {
     "expr": "zk_znode_count{instance=~\"$instance\"}",
     "legendFormat": "znode {{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo watches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_total_watches{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, mode) (zk_mode{instance=~\"$instance\"}) > 0",
     "legendFormat": " {{ mode }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, status) (zk_readwrite{instance=~\"$instance\"}) > 0",
     "legendFormat": "{{ instance }} {{ status }}"
    }
   ]
  },
  {
   "title": "Zoo packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(zk_packets_received{instance=~\"$instance\"}[$interval])",
     "legendFormat": "received {{ instance }}"
    },
    {
     "expr": "rate(zk_packets_sent{instance=~\"$instance\"}[$interval])",
     "legendFormat": "sent {{ instance }}"
    }
   ]
  },
  {
   "title": "zk_outstanding_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_outstanding_requests{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo num alive connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_num_alive_connections{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo max/open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{instance=~\"$instance\"}",
     "legendFormat": "open {{ instance }}"
    }
   ]
  },
  {
   "title": "Zoo latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_avg_latency{instance=~\"$instance\"}",
     "legendFormat": "avg {{ instance }}"
    },
    {
     "expr": "zk_max_latency{instance=~\"$instance\"}",
     "legendFormat": "max {{ instance }}"
    },
    {
     "expr": "zk_min_latency{instance=~\"$instance\"}",
     "legendFormat": "min {{ instance }}"
    }
   ]
  },
  {
   "title": "zk_ephemerals_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zk_ephemerals_count{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zk_approximate_data_size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zk_approximate_data_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}