{
 "title": "Alligator RabbitMQ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(rabbitmq_object_totals_channels,instance)"
    }
   },
   { "name": "interval", "query": "30s, 1m, 2m, 3m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) ((rabbitmq_object_totals_queues{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) ((rabbitmq_object_totals_consumers{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) ((rabbitmq_object_totals_connections{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) ((rabbitmq_object_totals_channels{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Nodes uptime",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min by (node) (rabbitmq_nodes_uptime{instance=~\"$instance\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Mem used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_nodes_mem_used{instance=~\"$instance\"}",
     "legendFormat": "{{ node }} read"
    }
   ]
  },
  {
   "title": "nodes_cluster_links rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_nodes_cluster_links{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} {{ type }} {{ dst }} {{ node }}"
    }
   ]
  },
  {
   "title": "gc bytes reclaimed rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_nodes_gc_bytes_reclaimed{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} {{ node }}"
    }
   ]
  },
  {
   "title": "gc num rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_nodes_gc_num{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} {{ node }}"
    }
   ]
  },
  { "title": "Cluster Disk State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "disk free",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_nodes_disk_free{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "fd used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rabbitmq_nodes_fd_used{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "IO bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(rabbitmq_nodes_io_read_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ node }} read"
    },
    {
     "expr": "rate(rabbitmq_nodes_io_write_bytes{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ node }} write"
    }
   ]
  },
  {
   "title": "io_file_handle_open_attempt rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_nodes_io_file_handle_open_attempt_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} {{ node }}"
    }
   ]
  },
  {
   "title": "io_file_handle_open_attempt_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rabbitmq_nodes_io_file_handle_open_attempt_avg_time{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ node }}"
    }
   ]
  },
  {
   "title": "IO avg time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rabbitmq_nodes_io_read_avg_time{instance=~\"$instance\"}",
     "legendFormat": "{{ node }} read"
    },
    {
     "expr": "rabbitmq_nodes_io_seek_avg_time{instance=~\"$instance\"}",
     "legendFormat": "{{ node }} seek"
    },
    {
     "expr": "rabbitmq_nodes_io_sync_avg_time{instance=~\"$instance\"}",
     "legendFormat": "{{ node }} sync"
    },
    {
     "expr": "rabbitmq_nodes_io_write_avg_time{instance=~\"$instance\"}",
     "legendFormat": "{{ node }} write"
    }
   ]
  },
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Vhost cluster state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node) (rabbitmq_vhosts_cluster_state{instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}{{name}} {{ node }}"
    }
   ]
  },
  {
   "title": "Vhost cluster size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_vhosts_cluster_size{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}{{name}}"
    }
   ]
  },
  {
   "title": "cluster_state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_vhosts_cluster_state{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}{{ name }} <> {{ node }}"
    }
   ]
  },
  {
   "title": "Total objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_object_totals_channels{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} channels"
    },
    {
     "expr": "rabbitmq_object_totals_connections{instance=~\"$instance\"}",
     "legendFormat": "{{ host }} connections"
    },
    {
     "expr": "rabbitmq_object_totals_consumers{instance=~\"$instance\"}",
     "legendFormat": "{{ host }} consumers"
    },
    {
     "expr": "rabbitmq_object_totals_exchanges{instance=~\"$instance\"}",
     "legendFormat": "{{ host }} exchanges"
    },
    {
     "expr": "rabbitmq_object_totals_queues{instance=~\"$instance\"}",
     "legendFormat": "{{ host }} queues"
    }
   ]
  },
  { "title": "Connections\\Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "connections_recv_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_recv_oct{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "connection created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_churn_rates_connection_created{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "minor_gcs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "targets": [
    {
     "expr": "rabbitmq_connections_gc_minor_gcs{instance=~\"$instance\"}",
     "legendFormat": "minor_gcs {{ instance }} {{ peer }}"
    }
   ]
  },
  {
   "title": "connections_recv_cnt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_recv_cnt{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "connection closed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_churn_rates_connection_closed{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "connection reductions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_reductions{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "connections_send_cnt",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_send_cnt{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "connection send pend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_send_pend{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "connections_send_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_send_oct{instance=~\"$instance\"}",
     "legendFormat": "{{ user }}@{{ instance }}{{vhost}} {{ peer }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  {
   "title": "channel created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_churn_rates_channel_created{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "connections_channels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_connections_channels{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{ protocol }} {{ auth_mechanism }}"
    }
   ]
  },
  { "title": "Queues\\Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "queues_state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "rabbitmq_queues_state{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} queues={{name}}"
    }
   ]
  },
  {
   "title": "queues stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queues_consumers{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}{{vhost}} {{name }} consumers"
    },
    {
     "expr": "rabbitmq_queues_durable{instance=~\"$instance\"}",
     "legendFormat": "{{ host }}{{vhost}} {{name }} durable"
    },
    {
     "expr": "rabbitmq_queues_exclusive{instance=~\"$instance\"}",
     "legendFormat": "{{ host }}{{vhost}} {{name }} exclusive"
    }
   ]
  },
  {
   "title": "Queues bytes unacknowledged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, vhost) (rabbitmq_queues_message_bytes_unacknowledged{instance=~\"$instance\"})",
     "legendFormat": "{{ name }}{{vhost}} unacknowledged"
    }
   ]
  },
  {
   "title": "Queues reductions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (name, vhost) (rate(rabbitmq_queues_reductions{instance=~\"$instance\"}[135s]))",
     "legendFormat": "{{ name }}{{vhost}}"
    }
   ]
  },
  {
   "title": "message_stats_disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_message_stats_disk_reads{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} reads"
    },
    {
     "expr": "rabbitmq_message_stats_disk_writes{instance=~\"$instance\"}",
     "legendFormat": "{{ host }} writes"
    }
   ]
  },
  {
   "title": "Queues messages unacknowledged",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name, vhost) (rabbitmq_queues_messages_unacknowledged{instance=~\"$instance\"})",
     "legendFormat": "{{ name }}{{vhost}} unacknowledged"
    },
    {
     "expr": "sum by (name, vhost) (rabbitmq_queues_messages_unacknowledged_ram{instance=~\"$instance\"})",
     "legendFormat": "{{ name }}{{vhost}} unacknowledged_ram"
    }
   ]
  },
  {
   "title": "Queue synchronised_slave_nodes_size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (name, vhost) (rabbitmq_queues_synchronised_slave_nodes_size{instance=~\"$instance\"})",
     "legendFormat": "{{ name }}{{vhost}}"
    }
   ]
  },
  {
   "title": "Incoming messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 117 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queues_backing_queue_status_avg_ack_ingress_rate{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Backing queue status rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queues_backing_queue_status_avg_ack_egress_rate{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}{{vhost}} {{name }} egress"
    },
    {
     "expr": "rabbitmq_queues_backing_queue_status_avg_ack_ingress_rate{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}{{vhost}} {{name }} inress"
    }
   ]
  },
  { "title": "Exchanges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "exchanges_internal",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_exchanges_internal{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{type}}:{{name}}"
    }
   ]
  },
  {
   "title": "exchanges_durable",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_exchanges_durable{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} {{type}}:{{name}}"
    }
   ]
  }
 ]
}