{
 "title": "Alligator aerospike",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(aerospike_status,instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(aerospike_master_objects{instance=~\"$instance\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client write per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(aerospike_client{type=\"write_success\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Query client types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, namespace) (rate(aerospike_client{instance=~\"$instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ type }} NS:{{ namespace}}"
    }
   ]
  },
  {
   "title": "Write errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "rate(aerospike_client{type=~\"(write_error|write_filtered_out|write_timeout)\", instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }} on {{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Client read per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(aerospike_client{type=\"read_success\", instance=~\"$instance\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "aerospike_batch_metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(aerospike_batch{instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }} on {{ instance }}"
    }
   ]
  },
  {
   "title": "Read/udf/proxy errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(aerospike_client{type=~\"(read_error|read_filtered_out|read_timeout|tsvc_error|tsvc_timeout|udf_error|udf_filtered_out|udf_timeout|proxy_error|proxy_timeout|lang_error)\", instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }} on {{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Migrations (Partitions)",
   "type": "timeseries",
   "description": "Migrations remaining migrate_tx_partitions_remaining (transmit), migrate_rx_partitions_remaining (receive)",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(aerospike_migrate{type=\"rx_partitions_remaining\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}{{service}}/{{namespace}} : Incoming "
    },
    {
     "expr": "(aerospike_migrate{type=\"tx_partitions_remaining\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}{{service}}/{{namespace}} : Outgoing "
    },
    {
     "expr": "(aerospike_migrate{type=\"rx_partitions_active\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}{{service}}/{{namespace}}: RX Active"
    },
    {
     "expr": "(aerospike_migrate{type=\"tx_partitions_active\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}{{service}}/{{namespace}} : TX Active "
    }
   ]
  },
  {
   "title": "Delete/lang errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(aerospike_client{type=~\"(delete_error|delete_filtered_out|delete_not_found|delete_timeout|lang_error|)\", instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ type }} on {{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Expired objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(aerospike_expired_objects{instance=~\"$instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "NS:{{ namespace}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_client_connections{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Evict stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(aerospike_evicted_objects{instance=~\"$instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "evicted_objects NS:{{ namespace}}"
    },
    {
     "expr": "sum by (namespace) (aerospike_evict_hist_buckets{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "hist_buckets NS:{{ namespace}}"
    },
    {
     "expr": "sum by (namespace) (aerospike_evict_tenths_pct{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "tenths_pct NS:{{ namespace}}"
    }
   ]
  },
  {
   "title": "Master objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, type) (aerospike_master_objects{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "{{ type }} NS:{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_cluster_size{instance=~\"$instance\"}",
     "legendFormat": "size on {{ instance }}"
    },
    {
     "expr": "aerospike_heartbeat_connections{instance=~\"$instance\"}",
     "legendFormat": "hearthbeat on {{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (aerospike_memory{type=\"used_bytes\", instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Memory NS:{{namespace}}"
    },
    {
     "expr": "sum by (namespace) (aerospike_device_used_bytes{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Device NS:{{namespace}}"
    },
    {
     "expr": "sum by (namespace) (aerospike_device_total_bytes{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "Device total. NS:{{namespace}}"
    }
   ]
  },
  {
   "title": "Disk stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, instance) (aerospike_device_used_bytes{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "used on {{ instance }}/{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, instance) (aerospike_device_total_bytes{instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "total on {{ instance }}/{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, instance) (disk_usage {type=\"total\", mountpoint=\"/\", instance=~\"$instance\", namespace=\"$namespace\"})",
     "legendFormat": "total disk size on {{ instance }}/{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, instance) (disk_usage {type=\"used\", mountpoint=\"/\",instance=~\"$instance\"})",
     "legendFormat": "disk usage on {{ instance }}/{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type, namespace) (aerospike_memory{instance=~\"$instance\", namespace=\"$namespace\", type!=\"free_pct\"})",
     "legendFormat": "{{ type }} NS:{{ namespace}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (aerospike_heap_active_kbytes{instance=~\"$instance\"})",
     "legendFormat": "active {{ instance }}"
    },
    {
     "expr": "sum by (instance) (aerospike_heap_allocated_kbytes{instance=~\"$instance\"})",
     "legendFormat": "allocated {{ instance }}"
    },
    {
     "expr": "sum by (instance) (aerospike_heap_mapped_kbytes{instance=~\"$instance\"})",
     "legendFormat": "mapped {{ instance }}"
    },
    {
     "expr": "sum by (instance) (memory_usage {instance=~\"$instance\"})/1024",
     "legendFormat": "total {{ instance }}"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type, namespace) (rate(aerospike_fail{instance=~\"$instance\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ type }} NS:{{ namespace}}"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace, type) (aerospike_info_queue{instance=~\"$instance\"})",
     "legendFormat": "info NS:{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, type) (rate(aerospike_storage_engine_post_write_queue{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "storage_engine_post_write_queue NS:{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, type) (aerospike_tree_gc_queue{instance=~\"$instance\"})",
     "legendFormat": "tree_gc NS:{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, type) (aerospike_tsvc_queue{instance=~\"$instance\"})",
     "legendFormat": "tsvc {{ namespace }}"
    },
    {
     "expr": "sum by (namespace, type) (aerospike_batch_queue{instance=~\"$instance\"})",
     "legendFormat": "info NS:{{ namespace }}"
    },
    {
     "expr": "sum by (namespace, type) (aerospike_delete_queue{instance=~\"$instance\"})",
     "legendFormat": "delete NS:{{ namespace }}"
    }
   ]
  },
  {
   "title": "free pct",
   "type": "timeseries",
   "description": "Percentage of memory capacity free for this namespace.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, aerospike_memory{type=\"free_pct\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Heartbeat received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(aerospike_heartbeat_received_foreign{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "foreign"
    },
    {
     "expr": "sum by (namespace) (rate(aerospike_heartbeat_received_self{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "self"
    }
   ]
  }
 ]
}