{
 "title": "Alligator system",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "query": {
     "query": "label_values(cores_num,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview $server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "server" },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cores_num{instance=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(disk_usage{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (host, type) (memory_usage{instance=~\"$server\", type=\"total\"})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cpu_usage_time{instance=~\"$server\", type!=\"idle\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - memory_usage_percent{instance=~\"$server\", type=\"free\"}"
    }
   ]
  },
  {
   "title": "Space (Lowest)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - min(disk_usage_percent{type=\"free\", instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "CPU model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(model)(cpu_model{instance=~\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(system_uptime_seconds{instance=~\"$server\"})"
    }
   ]
  },
  { "title": "CPU Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage - total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(cpu_usage_time{instance=~\"$server\", type!=\"idle\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cgroup Memory Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(memory_cgroup_fails{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} {{type }}"
    }
   ]
  },
  {
   "title": "Cgroup CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cpu_cgroup_throttled_seconds_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} {{type }}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(forks_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - forks rate"
    }
   ]
  },
  {
   "title": "Proccesses states",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_states {state=\"running\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - R state"
    },
    {
     "expr": "process_states{state=\"uninterruptible\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - D state"
    },
    {
     "expr": "process_states{state=\"zombie\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - Zombie"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(context_switches_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(interrupts_total{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - Interrupts"
    },
    {
     "expr": "rate(softirq{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - Soft Interrupts"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "System Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"dirty\"})",
     "legendFormat": "{{ instance }}- Dirty"
    },
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"shmem\"})",
     "legendFormat": "{{ instance }} - Shmem"
    },
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"mapped\"})",
     "legendFormat": "{{ instance }} - Mapped"
    },
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"wire\"})",
     "legendFormat": "{{ instance }} - Wire"
    },
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"real\"})",
     "legendFormat": "{{ instance }} - Real"
    }
   ]
  },
  {
   "title": "VM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=~\"(inactive|active|free).*\"})",
     "legendFormat": "{{ instance }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, type) (memory_usage{instance=~\"$server\", type=\"usage\"})",
     "legendFormat": "{{ instance }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(memory_stat {instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - Swap Transport In"
    },
    {
     "expr": "rate(memory_stat {instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - Swap Transport Out"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Sockets Activity: TCP established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "socket_counters{instance=~\"$server\", state=\"ESTABLISHED\", proto=\"tcp\"}",
     "legendFormat": "{{ instance }} {{ addr }} - {{ proto }} - {{ process }}"
    }
   ]
  },
  {
   "title": "Sockets Activity: TCP time_wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "socket_counters{instance=~\"$server\",state=\"TIME_WAIT\"}",
     "legendFormat": "{{ instance }} - {{proto}}"
    }
   ]
  },
  {
   "title": "Sockets Activity: others",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "socket_counters{instance=~\"$server\",state!=\"established\",state!=\"time_wait\"}",
     "legendFormat": "{{ instance }} - {{proto}} {{ state }}"
    }
   ]
  },
  {
   "title": "UDP stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "rate(network_stat_total {proto=~\"Udp.*\", instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ stat }}"
    }
   ]
  },
  {
   "title": "Network speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(if_stat {type=\"transmit_bytes\", instance=~\"$server\"}[$interval])*8",
     "legendFormat": "{{ instance }} - {{ifname}} outbound"
    },
    {
     "expr": "rate(if_stat {type=\"received_bytes\", instance=~\"$server\"}[$interval])*8",
     "legendFormat": "{{ instance }} - {{ifname}} inbound"
    }
   ]
  },
  {
   "title": "Packets rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(if_stat {type=\"transmit_packets\", instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ifname}} outbound packets"
    },
    {
     "expr": "rate(if_stat {type=\"received_packets\", instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ifname}} inbound packets"
    }
   ]
  },
  {
   "title": "TCP Sockets reciev queue length by limit (percent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "socket_stat_receive_queue_length{instance=~\"$server\", proto=~\"tcp|tcp6\"}/socket_stat_receive_queue_limit{instance=~\"$server\", proto=~\"tcp|tcp6\"}",
     "legendFormat": "{{ instance }} - {{proto}}:{{src_port}}"
    }
   ]
  },
  {
   "title": "TCP Sockets reciev queue length by limit ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "socket_stat_receive_queue_length{instance=~\"$server\", proto=~\"tcp|tcp6\"}",
     "legendFormat": "{{ instance }} - {{src_port}}"
    },
    {
     "expr": "socket_stat_receive_queue_limit{instance=~\"$server\", proto=~\"tcp|tcp6\"}",
     "legendFormat": "limit - {{instance}} - {{src_port}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "IOPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(disk_io {type=\"transfers_write\", instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - rate of writes per second"
    },
    {
     "expr": "rate(disk_io {type=\"transfers_read\",instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - rate reads per second"
    }
   ]
  },
  {
   "title": "% Busy rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(disk_busy{instance=~\"$server\"}[$interval])",
     "legendFormat": "{{ instance }} - {{dev}}"
    }
   ]
  },
  {
   "title": "disk device await",
   "type": "timeseries",
   "description": "the average time (in milliseconds) for I/O requests issued to the device to be served",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(disk_io_await_seconds_total{instance=~\"$server\", type=\"write\"}[$interval])",
     "legendFormat": "{{ instance }} - {{dev}} -write"
    },
    {
     "expr": "- rate(disk_io_await_seconds_total{instance=~\"$server\", type=\"read\"}[$interval])",
     "legendFormat": "{{ instance }} - {{dev}} -read"
    }
   ]
  },
  {
   "title": "I/O Await per iops",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "sum by (instance, dev) (rate(disk_io_await_seconds_total{instance=~\"$server\", type=\"read\"}[$interval])) / sum by (instance, dev) (rate(disk_io{instance=~\"$server\", type=\"transfers_read\"}[$interval]))",
     "legendFormat": "{{ instance }} - {{dev}} - read"
    },
    {
     "expr": "sum by (instance, dev) (rate(disk_io_await_seconds_total{instance=~\"$server\", type=\"write\"}[$interval])) / sum by (instance, dev) (rate(disk_io{instance=~\"$server\", type=\"transfers_write\"}[$interval]))",
     "legendFormat": "{{ instance }} - {{dev}} - write"
    }
   ]
  },
  {
   "title": "5 most used filesystems",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_usage_percent{type=\"used\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Open files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "open_files{instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - File descriptor statistics: allocated"
    },
    {
     "expr": "open_sockets{instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - Socket descriptor statistics: allocated"
    }
   ]
  },
  {
   "title": "Size of Filesystem",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "disk_usage {type=\"total\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "disk_usage_percent {type=\"used\", instance=~\"$server\"}",
     "legendFormat": "{{ instance }} - {{exported_instance}}"
    }
   ]
  },
  {
   "title": "CPU temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "core_temperature_celsius{instance=~\"$server\"}",
     "legendFormat": "{{ instance }} {{ component }}"
    }
   ]
  },
  {
   "title": "NUMA zones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum by (node, zone, size, instance) (buddyinfo_count {instance=~\"$server\", zone=\"Normal\" }) > 1000",
     "legendFormat": "{{ instance }} {{ zone }} {{ node }} size:{{ size }}"
    }
   ]
  }
 ]
}