{
 "title": "Alligator redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_uptime_in_seconds,instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s, 1m, 2m, 3m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max memory policy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum by(policy)(redis_maxmemory_policy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication count",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_role)(redis_role{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(redis_connected_slaves{instance=~\"$instance\"})",
     "legendFormat": "replica"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(redis_instantaneous_ops_per_sec{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 4 },
   "targets": [
    {
     "expr": "sum by(instance)(redis_connected_slaves{instance=~\"$instance\"})",
     "legendFormat": "Replicas {{ instance }}"
    }
   ]
  },
  {
   "title": "Sentinel count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "sentinel_sentinels{instance=~\"$instance\"}",
     "legendFormat": "Sentinels - {{instance}}"
    }
   ]
  },
  {
   "title": "Redis roles",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 11 },
   "targets": [
    {
     "expr": "redis_role{instance=~\"$instance\"} == 1"
    }
   ]
  },
  { "title": "Redis cpu, i/o, network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU usage and children usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(redis_used_cpu{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }} {{ type }}"
    }
   ]
  },
  {
   "title": "Memory util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_used_memory{instance=~\"$instance\",type=\"total\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "redis_maxmemory{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-max"
    }
   ]
  },
  {
   "title": "Used/Peak/RSS memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_used_memory{instance=~\"$instance\", type=~\"(total|rss|peak)\"}",
     "legendFormat": "{{ type }} - {{ instance }}"
    },
    {
     "expr": "redis_maxmemory{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - maxmemory"
    }
   ]
  },
  {
   "title": "Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "redis_instantaneous_input_kbps{instance=~\"$instance\"}",
     "legendFormat": "Input {{ instance }}"
    },
    {
     "expr": "redis_instantaneous_output_kbps{instance=~\"$instance\"}",
     "legendFormat": "Output {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio (rss/usage)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=~\"$instance\"} ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Clients connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Rejects connections",
   "type": "timeseries",
   "description": "Number of connections rejected due to hitting maxclient limit\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_rejected_connections{instance=~\"$instance\"}",
     "legendFormat": "Rejects  {{ instance }}"
    }
   ]
  },
  {
   "title": "Replication offset per sec",
   "type": "timeseries",
   "description": " The fragmentation is calculated as the physical memory actually used (the RSS value) divided by the amount of memory currently in use (as the sum of all the allocations performed by Redis). Because the RSS reflects the peak memory, when the (virtually) used memory is low since a lot of keys / values were freed, but the RSS is high, the ratio RSS / mem_used will be very high.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_master_repl_offset{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Keys statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Expired keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_expired_keys{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Evicted keys",
   "type": "timeseries",
   "description": "Number of evicted keys due to maxmemory limit\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_evicted_keys{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Seconds spent per command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "irate(redis_cmdstat_usec{instance=~\"$instance\"} [$interval])",
     "legendFormat": "{{instance}} - {{cmd}}"
    }
   ]
  },
  {
   "title": "Count items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_keys{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}-{{ db }}"
    }
   ]
  },
  {
   "title": "Keyspace hits and misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits{instance=~\"$instance\"}[$interval]) ",
     "legendFormat": "Hits {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Misses {{ instance }}"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "redis_keyspace_hits{instance=~\"$instance\"} / (redis_keyspace_hits{instance=~\"$instance\"} + redis_keyspace_misses{instance=~\"$instance\"}) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "New keys per db",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keys{instance=~\"$instance\"}[$interval]) ",
     "legendFormat": "{{ db }} {{ instance }} "
    }
   ]
  },
  {
   "title": "Keys per DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_keys{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{db}}"
    }
   ]
  },
  { "title": "Cluster mode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "cluster state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_cluster_state{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster messages received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_cluster_stats_messages_received{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster messages sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_cluster_stats_messages_sent{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster messages sent/received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_cluster_stats_messages_fail_sent{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - fail sent"
    },
    {
     "expr": "irate(redis_cluster_stats_messages_fail_received{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - fail received"
    }
   ]
  },
  {
   "title": "Cluster Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_cluster_slots_fail{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - fail"
    },
    {
     "expr": "redis_cluster_slots_ok{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - health"
    },
    {
     "expr": "redis_cluster_slots_pfail{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - pfail"
    }
   ]
  },
  {
   "title": "Config epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_cluster_current_epoch{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Persistence stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "AOF",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_aof_enabled{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "AOF rewrite",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_aof_rewrite_in_progress{instance=~\"$instance\"} ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "AOF rewrite duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_aof_current_rewrite_time_sec{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "RDB Changes Since Last Save",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(redis_rdb_changes_since_last_save{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RDB duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_time_sec{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - bgsave"
    }
   ]
  },
  {
   "title": "RDB Save",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 106 },
   "targets": [
    {
     "expr": "redis_rdb_bgsave_in_progress{instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RDB last cow size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 106 },
   "targets": [
    {
     "expr": "redis_rdb_last_cow_size{instance=~\"$instance\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}