{
 "title": "Alligator syslog-ng",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(syslogng_stats,instance)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s, 1m, 2m, 3m, 5m, 10m, 1h" }
  ]
 },
 "panels": [
  {
   "title": "Number of messages successfully delivered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(syslogng_stats{instance=\"$instance\", type=\"written\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ source_id }}"
    }
   ]
  },
  {
   "title": "Dropped messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(syslogng_stats{instance=\"$instance\", type=\"dropped\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ source_id }}"
    }
   ]
  },
  {
   "title": "Number of messages in queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(syslogng_stats{instance=\"$instance\", type=\"queued\"}[$interval])",
     "legendFormat": "{{ instance }} - {{ source_id }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "syslogng_stats{instance=\"$instance\", type=\"memory_usage\"}",
     "legendFormat": "{{ instance }} - {{ source_id }}"
    }
   ]
  }
 ]
}