- hosts: localhost
  tasks:

  - name: Copy rabbitmq.repo
    when: ansible_os_family == "RedHat"
    ansible.builtin.copy:
      src: ../misc/rabbitmq38.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Install pgpool
    yum:
      disable_gpg_check: True
      state: present
      name: 'https://www.pgpool.net/yum/rpms/4.2/redhat/rhel-8-x86_64/pgpool-II-release-4.2-1.noarch.rpm'
    when: ansible_os_family == "RedHat" and ansible_distribution_version > '7'

  - name: Install cutter-release
    when: ansible_os_family == "RedHat" and ansible_distribution_version < '8'
    yum:
      disable_gpg_check: True
      state: present
      name: 'https://acc.dl.osdn.jp/storage/g/c/cu/cutter/centos/cutter-release-1.3.0-1.noarch.rpm'

  - name: Install ius-release
    when: ansible_os_family == "RedHat" and ansible_distribution_version < '8'
    yum:
      state: present
      name: https://repo.ius.io/ius-release-el7.rpm

  - name: Install zookeeper-native
    when: ansible_os_family == "RedHat"
    yum:
      state: present
      disable_gpg_check: True
      name: https://t2.unl.edu/osg/3.4/el7/rolling/x86_64/zookeeper-native-3.4.5+cdh5.14.2+142-1.cdh5.14.2.p0.11.1.osg34.el7.x86_64.rpm

  - name: Install proxysql
    when: ansible_os_family == "RedHat" and ansible_distribution_version < '8'
    yum:
      state: present
      name: https://github.com/sysown/proxysql/releases/download/v2.0.16/proxysql-2.0.16-1-centos7.x86_64.rpm

  - name: Install nats-server
    when: ansible_os_family == "RedHat"
    yum:
      state: present
      disable_gpg_check: True
      name: https://github.com/nats-io/nats-server/releases/download/v2.1.9/nats-server-v2.1.9-amd64.rpm

  - name: Copy elasticsearch.repo
    when: ansible_os_family == "RedHat"
    ansible.builtin.copy:
      src: ../misc/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo

  - name: Copy datastax.repo
    when: ansible_os_family == "RedHat"
    ansible.builtin.copy:
      src: ../misc/datastax.repo
      dest: /etc/yum.repos.d/datastax.repo

  - name: Copy mongodb.repo
    when: ansible_os_family == "RedHat"
    ansible.builtin.copy:
      src: ../misc/mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Import a key from clickhouse repo
    when: ansible_os_family == "RedHat"
    ansible.builtin.rpm_key:
      state: present
      key: https://repo.clickhouse.tech/CLICKHOUSE-KEY.GPG

  - name: Add clickhouse repo
    when: ansible_os_family == "RedHat"
    yum_repository:
      name: clickhouse
      description: clickhouse repo
      file: clickhouse.repo
      baseurl: https://repo.clickhouse.tech/rpm/stable/x86_64
      enabled: yes

  - name: install freebsd
    when: ansible_os_family == "FreeBSD"
    ansible.builtin.package:
      state: present
      name:
      - autoconf-wrapper
      - mysql80-client
      - openjdk16
      - vim
      - rubygem-rake
      - autotools
      - json-yaml #/usr/local/bin/yaml-json /etc/alligator.yaml

  - name: install debian == 10
    when: ansible_os_family == "Debian" and ansible_distribution_major_version == "10"
    ansible.builtin.package:
      state: present
      name:
      - default-libmysqlclient-dev

  - name: install ubuntu >= 18
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16"
    ansible.builtin.package:
      state: present
      name:
      - libmysqlclient-dev
      - openjdk-11-jdk

  - name: install debian 10
    when: ansible_os_family == "Debian"
    ansible.builtin.package:
      state: present
      name:
      - libnfnetlink-dev
      - libudev-dev
      - cmake
      - libzookeeper-mt-dev
      - openjdk-11-jdk
      - curl

  - name: install debian
    when: ansible_os_family == "Debian" and ansible_distribution_version >= '16'
    ansible.builtin.package:
      state: present
      name:
      - libnfnetlink-dev
      - libudev-dev
      - cmake
      - libzookeeper-mt-dev
      - curl
      - autoconf

  - name: install ubuntu
    when: ansible_os_family == "Debian" and ansible_distribution_version <= '16'
    ansible.builtin.package:
      state: present
      name:
      - redis-server

  - name: install ubuntu 18
    when: ansible_os_family == "Debian" and ansible_distribution_version <= '18'
    ansible.builtin.package:
      state: present
      name:
      - netcat-openbsd
      - make
      - autoconf

  - name: install el
    when: ansible_os_family == "RedHat"
    ansible.builtin.package:
      state: present
      skip_broken: yes
      allow_downgrade: yes
      name:
      - epel-release
      - python3-devel
      - systemd-devel
      - postgresql-devel
      - java-latest-openjdk-devel
      - libuuid-devel
      - rpm-devel
      - nc
      - mariadb-devel
      - mariadb-server
      - postgresql-server
      - postgresql-static
      - nmap-ncat
      - rpmdevtools
      - redhat-rpm-config
      - epel-rpm-macros
      - elasticsearch
      - createrepo
      - gearmand
      - openssl-libs
      - openssl-devel
      - libsodium-devel
      - httpd
      - clickhouse-server
      - redis
      - monit
      - gcc-c++
      - go
      - mongodb-org-server
      - mongodb-org-shell

  - name: Install el7
    when: ansible_os_family == "RedHat" and ansible_distribution_version < '8'
    ansible.builtin.package:
      state: present
      skip_broken: yes
      allow_downgrade: yes
      name:
      - postgresql-pgpool-II
      - mysql-proxy-devel
      - mysql-proxy
      - libpqxx-devel
      - cutter
      - beanstalkd
      - uwsgi
      - uwsgi-plugin-python36
      - cmake3
      - vim-go

  - name: Install el8
    when: ansible_os_family == "RedHat" and ansible_distribution_version >= '8'
    ansible.builtin.package:
      state: present
      skip_broken: yes
      allow_downgrade: yes
      name:
      - pgpool-II-pg13
      - cmake
      - libarchive-3.3.3
      - gdb

  - name: Install general Linux
    when: ansible_system == "Linux"
    ansible.builtin.package:
      state: present
      name:
      - git
      - vim
      - pgbouncer
      - sudo
      - jq
      - nsd
      - unbound
      - python3-pip
      - gcc
      - wget
      - make
      - libtool
      - valgrind
      - rake
      - rsyslog
      - unbound
      - varnish
      - nginx
      - rabbitmq-server
      - haproxy
      - openssl
      - rabbitmq-server
      - python3
      - nginx
      - varnish
      - squid
      - lighttpd
      - xinetd
      - tftp-server

  - name: Create /data/db directory
    file:
      path: /data/db/
      state: directory
      owner: mongod
      group: mongod


  - name: Create a symbolic link force
    when: ansible_system == "FreeBSD"
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dst }}'
      state: link
    loop:
    - dst: /usr/local/bin/vi
      src: /usr/local/bin/vim

  - name: Create a symbolic link force
    when: ansible_system == "Linux"
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dst }}'
      state: link
      force: yes
    loop:
    - dst: /usr/bin/vi
      src: /usr/bin/vim
    - dst: /usr/bin/pip
      src: /usr/bin/pip3

  - name: Create a symbolic link force el7
    when: ansible_os_family == "RedHat" and ansible_distribution_version < '8'
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dst }}'
      state: link
      force: yes
    loop:
    - dst: /usr/bin/cmake
      src: /usr/bin/cmake3

  - name: Create a symbolic link force gmake
    when: ansible_os_family == "Debian"
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dst }}'
      state: link
    loop:
    - dst: /usr/bin/gmake
      src: /usr/bin/make

  - name: Install pip deps
    when: ansible_system == "Linux"
    pip:
      executable: pip3
      name:
      - statsd
      - conan
      - 'MarkupSafe==1.0.0'

  - name: Install pip deps
    when: ansible_system == "FreeBSD"
    pip:
      executable: pip-3.8
      name:
      - statsd
      - conan
